names := svetlana ruslana bilana

eee: $(names)

#svetlana: prereq
#ruslana: prereq
#bilana: prereq

%lana:
	touch $@

print: $(wildcard *ana)
	ls -al $?

create_c:
	touch 1.c
	touch 2.c
	touch 3.c
	touch 4.c
	touch 5.c
create_random:
	touch random1
	touch random2
	touch random3
	touch random4
	touch random5

clean_c:
	rm -f *ana